default: &defaults
  push_api_key: <%= Settings.app_signal.key %>
  name: "Compliance Bitex.la"
  ignore_errors:
    - SystemExit
  debug: false
  sample: 25
  active: true

development:
  <<: *defaults
  name: <%= "#{Settings.app_signal.app} dev" %>
  sample: 100
  debug: true
  active: false

production:
  <<: *defaults
  name: <%= "#{Settings.app_signal.app} prod" %>

staging:
  <<: *defaults
  active: true
  name: <%= "#{Settings.app_signal.app} staging" %>
