default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  push_api_key: <%= ENV.fetch('APPSIGNAL_PUSH_API_KEY' ){ '' } %>

  # Your app's name
  name: <%= ENV.fetch('APPSIGNAL_APP_NAME' ){ 'Open Compliance' } %> 

  ignore_errors:
    - SystemExit

  debug: <%= ENV.fetch('APPSIGNAL_DEBUG' ){ false } %> 

  # Will send <sample>/100 datapoints on average, picked randomly
  sample: <%= ENV.fetch('APPSIGNAL_SAMPLE' ){ 50 } %> 

  active: <%= ENV.fetch('APPSIGNAL_ACTIVE' ){ true } %> 

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  <<: *defaults
  name: <%= ENV.fetch('APPSIGNAL_APP_NAME' ){ 'Open Compliance (dev)' } %>  
  sample: <%= ENV.fetch('APPSIGNAL_SAMPLE' ){ 100 } %> 
  debug: <%= ENV.fetch('APPSIGNAL_DEBUG' ){ true } %>
  active: <%= ENV.fetch('APPSIGNAL_ACTIVE' ){ false } %>

production:
  <<: *defaults

staging:
  <<: *defaults
  active: <%= ENV.fetch('APPSIGNAL_ACTIVE' ){ true } %>
  name: <%= ENV.fetch('APPSIGNAL_APP_NAME' ){ 'Open Compliance (staging)' } %> 
