defaults: &defaults
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE'){ 'secret_key' } %>

  s3:
    aws_access_key_id: <%= ENV.fetch('S3_ACCESS_KEY'){ '____c' } %>
    aws_secret_access_key: <%= ENV.fetch('S3_SECRET_KEY'){ '____' } %>
    attachments_bucket: <%= ENV.fetch('S3_BUCKET'){ 'production' } %>

  ses:
    access_key: <%= ENV.fetch('SES_ACCESS_KEY'){ 'some_access_key' } %>
    secret: <%= ENV.fetch('SES_SECRET'){ 'some_secret' } %>

  sqs:
    credentials:
      access_key_id: <%= ENV.fetch('SQS_ACCESS_KEY'){ 'some_access_key' } %>
      secret_access_key: <%= ENV.fetch('SQS_SECRET'){ 'some_secret' } %>
      region: <%= ENV.fetch('SQS_REGION'){ 'us-east-1' } %>

    port: 9324
    queue: <%= ENV.fetch('SQS_QUEUE'){ 'queue_url' } %>
    publish: true

  mysql:
    pool: <%= ENV.fetch('MYSQL_POOL'){ 5 } %>
    username: <%= ENV.fetch('MYSQL_USERNAME'){ 'root' } %>
    password: <%= ENV.fetch('MYSQL_PASSWORD'){ '' }  %>
    host: <%= ENV.fetch('MYSQL_HOST'){ '127.0.0.1' } %>
    port: <%= ENV.fetch('MYSQL_PORT'){ 3306 } %>

  exception_recipients: <%= ENV.fetch('EXCEPTION_RECIPIENTS'){ 'some@me.com,other@me.com' } %>

  regularities:
    low:
      funding_amount: 2500
      funding_count: 3
    high:
      funding_amount: 10000
      funding_count: 10

  lock_issues:
    expiration_interval_minutes: 15

  app_signal:
    key: <%= ENV.fetch('APP_SIGNAL_KEY' ){ 'fjkdjflkdjflkdjfdkl' } %> 
    app: <%= ENV.fetch('APP_SIGNAL_APP' ){ 'Compliance' } %> 

  redis:
    cache_url: <%= ENV.fetch('REDIS_CACHE_URL' ){ 'redis://localhost:6379/0' } %>
    namespace: <%= ENV.fetch('REDIS_NAMESPACE' ){ 'compliance' } %> 
    pool_size: <%= ENV.fetch('REDIS_POOL_SIZE' ){ 8 } %>

  cache_store: <%= ENV.fetch('CACHE_STORE' ){ '/tmp/cache/compliance' } %>

  observation_token_hours: 2160 # 90 days

  cors:
    allowed_origins: '*'
    debug: false

production:
  <<: *defaults

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
