class Currency 
  include StaticModels::Model

  static_models_dense [
    [:id, :code, :name,                :decimals ],
    [1,   :btc,  'bitcoin',            4         ],
    [2,   :ltc,  'litecoin',           4         ],
    [3,   :bch,  'bcash',              4         ],
    [4,   :usd,  'us_dollar',          2         ],
    [5,   :ars,  'argentine_peso',     2         ],
    [6,   :uyu,  'uruguayan_peso',     2         ],
    [7,   :eur,  'euro',               2         ],
    [8,   :clp,  'chilean_peso',       2         ],
    [9,   :pen,  'peruvian_sol',       2         ],
    [10,  :brl,  'brazilian_real',     2         ],
    [11,  :cop,  'colombian_peso',     2         ],
    [12,  :mxn,  'mexican_peso',       2         ],
    [13,  :pyg,  'paraguayan_guarani', 2         ],
    [14,  :cny,  'chinese_yuan',       2         ],
    [15,  :inr,  'indian_rupee',       2         ],
    [16,  :vef,  'venezuelan_bolivar', 2         ],
    [17,  :aud,  'australian_dollar',  2         ],
    [18,  :gbp,  'pound_sterling',     2         ],
    [19,  :hkd,  'hong_kong_dollar',   2         ],
    [20,  :bob,  'bolivian_peso',      2         ],
    [21,  :ada,  'ada',                8         ],
    [22,  :bnb,  'binance_coin',       8         ],
    [23,  :dai,  'dai',                8         ],
    [24,  :eth,  'ethereum',           8         ],
    [25,  :link, 'link',               8         ],
    [26,  :sushi,'sushi',              8         ],
    [27,  :uni,  'uni',                8         ],
    [28,  :usdt, 'usd_tether',         8         ],
    [29,  :ftt,  'ftt',                8         ],
    [30,  :yfi,  'yfi',                8         ],
    [31,  :dot,  'dot',                8         ],
    [32,  :doge, 'doge',               8         ],
    [33,  :soya, 'soya',               8         ],
    [34,  :usdc, 'usdc',               2         ],
    [35,  :sol,  'sol',                8         ],
    [36,  :cora, 'cora',                    8        ],
    [37,  :brz,  'brazilian_digital_token', 8        ],
    [38,  :shib, 'shiba_inu',               8        ],
    [39,  :mana, 'mana',                    8        ],
    [40,  :chz,  'chiliz',                  8        ],
    [41,  :xlm,  'stellar',                 8        ],
    [42,  :xrp,  'ripple',                  8        ],
  ]
end
